workflows:
  ios-release:
    name: iOS Release
    instance_type: mac_mini_m2
    max_build_duration: 120

    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: Flutter clean
        script: |
          flutter clean
          flutter pub get

      - name: Build IPA
        script: |
          flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      - name: Publish to TestFlight
        app_store_connect:
          api_key:
            key_id: $APP_STORE_CONNECT_KEY_ID
            issuer_id: $APP_STORE_CONNECT_ISSUER_ID
            private_key: $APP_STORE_CONNECT_PRIVATE_KEY
          submit_to_testflight: true
