workflows:
  ios-release:
    name: iOS Release
    instance_type: mac_mini_m2
    max_build_duration: 120

    environment:
      groups:
        - app_store_credentials  # Make sure this group exists in Codemagic UI
      flutter: stable
      xcode: latest

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
          source: true

    scripts:
      - name: Setup and dependencies
        script: |
          flutter --version
          flutter config --no-analytics
          flutter clean
          rm -rf ios/Pods ios/.symlinks
          flutter pub get
          
      - name: Build iOS app
        script: |
          cd ios
          pod install --repo-update
          cd ..
          flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      email:
        recipients:
          - your-email@example.com
      
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        # Optional: Add beta groups if needed
        # beta_groups:
        #   - "Testers"